[package]
name = "papr-tokenizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
papr = { path = "../../" }
nom = "*"
clap = { version = "*", features = ["derive"] }
pest = "*"
