[package]
name = "papr"
version = "0.1.0"
edition = "2021"

[features]
default = ["double"]
double = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
cfg-if = "1.0.0"
clap = { version = "4.3.19", features = ["derive"] }
cpal = "0.15.2"
dyn-clone = "1.0.12"
eframe = "0.22.0"
nom = "7.1.3"
petgraph = "0.6.3"
rustc-hash = "1.1.0"
tokio = { version = "1.29.1", features = ["full"] }
